version: "3.8"

services:
  neoberry:
    container_name: neoberry_app
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_SECRET_KEY=changeme
    restart: unless-stopped

