version: '3.8'
services:
  neoberry:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    privileged: true  # Nécessaire pour accéder aux GPIO
    devices:
      - "/dev/gpiomem:/dev/gpiomem"  # Accès aux GPIO
    environment:
      - FLASK_ENV=development
    command: python app/main.py
